"""Updated Package 6

Revision ID: 7719343488a1
Revises: d819de60582c
Create Date: 2024-11-10 14:48:28.137198

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7719343488a1'
down_revision = 'd819de60582c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Estimated_Price', schema=None) as batch_op:
        batch_op.alter_column('estimated_price',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=True)

    with op.batch_alter_table('Exclusion', schema=None) as batch_op:
        batch_op.alter_column('exclusion',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)

    with op.batch_alter_table('Inclusion', schema=None) as batch_op:
        batch_op.alter_column('inclusion',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)

    with op.batch_alter_table('Itinerary', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('subtitle', sa.String(length=100), nullable=True))
        batch_op.drop_column('itinerary')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Itinerary', schema=None) as batch_op:
        batch_op.add_column(sa.Column('itinerary', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
        batch_op.drop_column('subtitle')
        batch_op.drop_column('title')

    with op.batch_alter_table('Inclusion', schema=None) as batch_op:
        batch_op.alter_column('inclusion',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)

    with op.batch_alter_table('Exclusion', schema=None) as batch_op:
        batch_op.alter_column('exclusion',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)

    with op.batch_alter_table('Estimated_Price', schema=None) as batch_op:
        batch_op.alter_column('estimated_price',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=False)

    # ### end Alembic commands ###
