"""Complete Database

Revision ID: 7952ab66fea8
Revises: 
Create Date: 2024-11-05 23:33:09.657841

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7952ab66fea8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_admin')
    op.drop_table('user_traveler')
    op.drop_table('user_tour_operator')
    with op.batch_alter_table('Characteristic', schema=None) as batch_op:
        batch_op.create_index('idx_characteristic_tguide_id', ['tguide_id'], unique=False)

    with op.batch_alter_table('Skill', schema=None) as batch_op:
        batch_op.create_index('idx_skill_tguide_id', ['tguide_id'], unique=False)

    with op.batch_alter_table('Tour_Guide', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('toperator_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=True))
        batch_op.add_column(sa.Column('contact_num', sa.String(length=15), nullable=True))
        batch_op.drop_constraint('Tour_Guide_email_key', type_='unique')
        batch_op.create_index('idx_tour_guide_active', ['active'], unique=False)
        batch_op.create_index('idx_tour_guide_toperator_id', ['toperator_id'], unique=False)
        batch_op.create_index('idx_tour_guide_user_id', ['user_id'], unique=False)
        batch_op.create_unique_constraint(None, ['user_id'])
        batch_op.create_foreign_key(None, 'Users', ['user_id'], ['id'])
        batch_op.create_foreign_key(None, 'Tour_Operator', ['toperator_id'], ['id'])
        batch_op.drop_column('contact_number')
        batch_op.drop_column('lname')
        batch_op.drop_column('fname')
        batch_op.drop_column('image_file')
        batch_op.drop_column('password')
        batch_op.drop_column('confirmed')
        batch_op.drop_column('role')
        batch_op.drop_column('email')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Tour_Guide', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('role', sa.VARCHAR(length=30), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('confirmed', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('password', sa.VARCHAR(length=250), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('image_file', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('fname', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('lname', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('contact_number', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_index('idx_tour_guide_user_id')
        batch_op.drop_index('idx_tour_guide_toperator_id')
        batch_op.drop_index('idx_tour_guide_active')
        batch_op.create_unique_constraint('Tour_Guide_email_key', ['email'])
        batch_op.drop_column('contact_num')
        batch_op.drop_column('price')
        batch_op.drop_column('toperator_id')
        batch_op.drop_column('user_id')

    with op.batch_alter_table('Skill', schema=None) as batch_op:
        batch_op.drop_index('idx_skill_tguide_id')

    with op.batch_alter_table('Characteristic', schema=None) as batch_op:
        batch_op.drop_index('idx_characteristic_tguide_id')

    op.create_table('user_tour_operator',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('email', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('password', sa.VARCHAR(length=250), autoincrement=False, nullable=False),
    sa.Column('role', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('image_file', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('confirmed', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='user_tour_operator_pkey'),
    sa.UniqueConstraint('email', name='user_tour_operator_email_key')
    )
    op.create_table('user_traveler',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('first_name', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('last_name', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('nationality', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('password', sa.VARCHAR(length=150), autoincrement=False, nullable=False),
    sa.Column('role', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('image_file', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('confirmed', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='user_traveler_pkey'),
    sa.UniqueConstraint('email', name='user_traveler_email_key')
    )
    op.create_table('user_admin',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('email', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('password', sa.VARCHAR(length=250), autoincrement=False, nullable=False),
    sa.Column('role', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('confirmed', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='user_admin_pkey'),
    sa.UniqueConstraint('email', name='user_admin_email_key')
    )
    # ### end Alembic commands ###
