"""Updated Package 2

Revision ID: 879304f87921
Revises: 
Create Date: 2024-11-10 12:17:57.735655

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '879304f87921'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('TourPackage', schema=None) as batch_op:
        batch_op.add_column(sa.Column('toperator_id', sa.Integer(), nullable=False))
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
        batch_op.create_index('idx_tour_package', ['toperator_id'], unique=False)
        batch_op.create_foreign_key(None, 'Tour_Operator', ['toperator_id'], ['id'])
        batch_op.drop_column('itinerary')
        batch_op.drop_column('estimated_price')
        batch_op.drop_column('exclusion')
        batch_op.drop_column('inclusion')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('TourPackage', schema=None) as batch_op:
        batch_op.add_column(sa.Column('inclusion', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('exclusion', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('estimated_price', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('itinerary', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index('idx_tour_package')
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.drop_column('toperator_id')

    # ### end Alembic commands ###
