"""Updated Package 4

Revision ID: d819de60582c
Revises: 0d10ff7376d1
Create Date: 2024-11-10 12:29:35.709278

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd819de60582c'
down_revision = '0d10ff7376d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('TourPackage', schema=None) as batch_op:
        batch_op.add_column(sa.Column('package_img', sa.String(length=225), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('TourPackage', schema=None) as batch_op:
        batch_op.drop_column('package_img')

    # ### end Alembic commands ###
